// Get vehicle type
export const GET_VEHICLE_TYPE_LIST = 'GET_VEHICLE_TYPE_LIST';
export const GET_VEHICLE_TYPE_LIST_SUCCESS = 'GET_VEHICLE_TYPE_LIST_SUCCESS';
export const GET_VEHICLE_TYPE_LIST_FAILURE = 'GET_VEHICLE_TYPE_LIST_FAILURE';

// Get vehicle type details
export const GET_VEHICLE_TYPE_DETAILS = 'GET_VEHICLE_DETAILS';
export const GET_VEHICLE_DETAILS_SUCCESS = 'GET_VEHICLE_DETAILS_SUCCESS';
export const GET_VEHICLE_DETAILS_FAILURE = 'GET_VEHICLE_DETAILS_FAILURE';
