// <auto-generated />
using CarSales.Web.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarSales.Web.Infra.Data.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20200620093800_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("CarSales.Web.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Doors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<int>("Wheels")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            Doors = 4,
                            Make = "Hyundai / Kia",
                            Model = "Toyota Hilux",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 2,
                            Doors = 4,
                            Make = "Group PSA",
                            Model = "Hyundai Tucson",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 3,
                            Doors = 4,
                            Make = "Group PSA",
                            Model = "Toyota Hilux",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 4,
                            Doors = 4,
                            Make = "Nissan",
                            Model = "Ford Ranger",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 5,
                            Doors = 4,
                            Make = "FCA",
                            Model = "Ford Ranger",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 6,
                            Doors = 4,
                            Make = "Nissan",
                            Model = "Toyota Corolla",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 7,
                            Doors = 4,
                            Make = "FCA",
                            Model = "Toyota Corolla",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 8,
                            Doors = 4,
                            Make = "Group PSA",
                            Model = "Hyundai i30",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 9,
                            Doors = 4,
                            Make = "Nissan",
                            Model = "Hyundai Tucson",
                            Wheels = 4
                        },
                        new
                        {
                            VehicleId = 10,
                            Doors = 4,
                            Make = "General Motors",
                            Model = "Toyota Hilux",
                            Wheels = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
